### ISSUE TITLE
Incorrect parse of jsdoc comments in class methods

### ISSUE THREAD

**Issue by VasilyAK** [ctumolosus/jsdoc-babel#100]
Windows 10.

Example:

    class Test {
        /** comment 1 */
        firstMethod() {}

        /** comment 2 */
        secondMethod() {}
    }

after parse coment 2 is a part of firstMethod code.

    "use strict";
    var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");
    Object.defineProperty(exports, "__esModule", {
        value: true
    });
    exports.default = void 0;
    var _classCallCheck2 = _interopRequireDefault(require("@babel/runtime/helpers/classCallCheck"));
    var _createClass2 = _interopRequireDefault(require("@babel/runtime/helpers/createClass"));
    var Test =/*#__PURE__*/function () {
        function Test() {
            (0, _classCallCheck2.default)(this, Test);
        }
        (0, _createClass2.default)(Test, [{
            key: "firstMethod",
            /** comment 1 \*/
            value: function firstMethod() {}
            /** comment 2 */ <== (this is wrong)
        }, {
            key: "secondMethod",
            value: function secondMethod() {}
        }]);
        return Test;
    }();
    var _default = cache;
    exports.default = _default;

**Comment by ctumolosus** [comment]
That is the output after your code is transformed with Babel. If you try transforming the code outside of the plugin (e.g. using Babel REPL https://babeljs.io/en/repl) you should see similar results. Did you find the generated documentation was incorrect as a result of this?

**Comment by VasilyAK** [comment]
Yes it is. My generated documentation does not describe methods for which babel parsed incorrectly.

**Comment by ctumolosus** [comment]
@VasilyAK Looked into this further and it works for me after adding a `@class` annotation:

```javascript
/**
 * @class Test
 */
class Test {
  /** comment 1 */
  firstMethod() {}

  /** comment 2 */
  secondMethod() {}
}
```

The reason I added `@class` is because the transformed code does not hint to JSDoc that it is intended to be a `class`. 

```javascript
var Test =/*#__PURE__*/function () {
    function Test() {
        (0, _classCallCheck2.default)(this, Test);
    }
    ...
}
```
Curious, have you tried using JSDoc without this plugin? The latest version should be able to handle ES6 out of the box. This plugin was created as a stepping stone until JSDoc supported parsing for ES6 years ago.

**Comment by VasilyAK** [comment]
I use this plugin because I use flow to typify js code.

I intentionally did not use @class, as I tried to describe only one specific instance of the class, inheriting the description of methods via @namespace and @memberof.

Incorrect analysis is the only thing that interfered with my plan.

**Comment by ctumolosus** [comment]
Based on your comment it sounds like you are having issues annotating the transformed code to achieve the results you want. Perhaps, you can use the [`@hideconstructor`](https://jsdoc.app/tags-hideconstructor.html) annotation or change the transform target to ES2015. I'm not sure the latter will yield different results since the `class` keyword most likely is handled as `@class` when parsed in JSDoc.

**Comment by VasilyAK** [comment]
Thanks for the help. I’ll think about how else I can solve my problem.
